from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional, Union

import torch


@dataclass
class Sample:
    """The sample generated"""

    group_index: Optional[int] = None
    index: Optional[int] = None
    # prompt
    prompt: Union[str, list[dict[str, str]]] = ""
    tokens: list[int] = field(default_factory=list)
    # response
    response: str = ""
    response_length: int = 0
    label: Optional[str] = None
    reward: Optional[Union[float, dict[str, Any]]] = None
    loss_mask: Optional[list[int]] = None
    weight_versions: list[str] = field(default_factory=list)
    rollout_log_probs: Optional[list[float]] = None  # Log probabilities from rollout engine
    rollout_routed_experts: Optional[list[list[int]]] = None  # Routed experts from rollout engine
    policy_version: Optional[int] = None  # Policy version that generated this sample (for off-policy tracking)

    class Status(Enum):
        PENDING = "pending"
        COMPLETED = "completed"
        TRUNCATED = "truncated"
        ABORTED = "aborted"

    status: Status = Status.PENDING

    metadata: dict = field(default_factory=dict)
    # metadata used during training, e.g., what loss to use for this sample.
    train_metadata: Optional[dict] = None

    class SpecInfo:
        spec_accept_token_num: int = 0
        spec_draft_token_num: int = 0
        spec_verify_ct: int = 0
        spec_accept_rate: float = 0.0
        spec_accept_length: float = 0.0

        def add(self, meta_info: dict, response_length: int):
            self.spec_accept_token_num += meta_info["spec_accept_token_num"]
            self.spec_draft_token_num += meta_info["spec_draft_token_num"]
            self.spec_verify_ct += meta_info["spec_verify_ct"]
            if self.spec_draft_token_num > 0:
                # Notice: this does not iclude the bonus token generated by verify step.
                self.spec_accept_rate = self.spec_accept_token_num / self.spec_draft_token_num
            # self.spec_accept_rate = meta_info["spec_accept_rate"] #
            if self.spec_verify_ct > 0:
                self.spec_accept_length = response_length / self.spec_verify_ct

    spec_info: SpecInfo = field(default_factory=SpecInfo)

    def to_dict(self):
        value = self.__dict__.copy()
        value["status"] = self.status.value
        return value

    @staticmethod
    def from_dict(data: dict):
        data["status"] = Sample.Status(data["status"])
        return Sample(**data)

    def get_reward_value(self, args) -> float:
        """
        Get reward value, handling both scalar and dict rewards.

        Args:
            args: Configuration with optional reward_key

        Returns:
            Float reward value (never None, fallback to 0)
        """
        # Handle None reward (should not happen after fixes, but be defensive)
        if self.reward is None:
            print(f"[WARNING] get_reward_value: reward is None, returning 0")
            return 0

        # If no reward_key specified, return scalar reward
        if not args.reward_key:
            return self.reward

        # reward_key is specified - reward should be a dict
        if isinstance(self.reward, dict):
            # Return the specified key, or 0 if key doesn't exist
            value = self.reward.get(args.reward_key, 0)
            if value is None:
                print(f"[WARNING] get_reward_value: reward[{args.reward_key}] is None, returning 0")
                return 0
            return value
        else:
            # Configuration mismatch: reward_key set but reward is scalar
            # This happens when reward function returns scalar but args expects dict
            print(f"[WARNING] get_reward_value: reward_key='{args.reward_key}' is set but "
                  f"reward is scalar ({self.reward}). Returning scalar value.")
            return self.reward

    @property
    def effective_response_length(self):
        return sum(self.loss_mask) if self.loss_mask is not None else self.response_length


@dataclass
class ParamInfo:
    name: str
    dtype: torch.dtype
    shape: torch.Size
    attrs: dict
    size: int
    src_rank: int


# A dict-based batch produced along the rollout -> training path
# In Megatron backend, several fields are converted to torch.Tensor lists on GPU
# before being consumed by data iterators (see megatron_utils.actor._get_rollout_data).
RolloutBatch = dict[str, list[torch.Tensor] | list[int] | list[float] | list[str]]
